name: explode and deploy overlay image

on:
  push:
    branches:
      - wftest

jobs:
  docs:
    if: github.repository == 'r-PlaceTux/Overlay'
    runs-on: ubuntu-latest
    steps:
      - name: list dir
        run: 'tree /'
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.12'
      - name: explode image
        run: poetry run ./Overlay/explode_overlay.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/
          keep_files: true
          full_commit_message: deploy image